In [1]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

my_list = my_array.tolist()

print(my_list)

[1, 2, 3, 4, 5]


In [3]:
my_array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

diagonal_sum1 = 0
for i in range(my_array1.shape[0]):
    diagonal_sum1 += my_array1[i][i]

print(diagonal_sum1)

15


In [5]:
my_array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

diagonal_sum2 = np.trace(my_array2)

print(diagonal_sum2)

15


In [6]:
my_array3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

number = 5
for i in range(my_array3.shape[0]):
    for x in range(my_array3.shape[1]):
        if my_array3[i][x] > number:
            print(my_array3[i][x])

6
7
8
9


In [12]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
c = np.array([[0,0],[0,0]])

for l in range(x.shape[0]):
    for k in range(x.shape[1]):
        c[l][k]=x[l][k]+y[l][k]
print(c)

[[ 6  8]
 [10 12]]


In [33]:
my_array4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

row_means = np.mean(my_array4, axis=1)
a = row_means.reshape(-1,1)
a = a.astype(np.int32)
my_array4 -= a
print(row_means)
print(a)
print(my_array4)

[2. 5. 8.]
[[2]
 [5]
 [8]]
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
